backend:
  name: github
  repo: geny7i/geny7i.dev
  branch: main
media_folder: "static/images"
public_folder: "public"
publish_mode: editorial_workflow
collections:
  - name: "posts"
    label: "posts"
    folder: "content/post"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Date", name: "date", widget: "date", required: true}
      - {label: "Tags", name: "tags", widget: "list",default: ["Rails", "Ruby", "PHP", "Laravel", "Hugo"], required: true}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown", required: true}